# Generated by Django 4.2.25 on 2025-11-02 14:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'software_licenses',
                'indexes': [models.Index(fields=['name'], name='software_li_name_e97159_idx')],
            },
        ),
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('number_of_tracks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'db_table': 'music_albums',
                'indexes': [models.Index(fields=['artist'], name='music_album_artist_0c6e8c_idx'), models.Index(fields=['title'], name='music_album_title_ebe7bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('number_of_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'db_table': 'books',
                'indexes': [models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['title'], name='books_title_7a737c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'cart_items',
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['cart', 'content_type', 'object_id'], name='cart_items_cart_id_443dd8_idx')],
                'unique_together': {('cart', 'content_type', 'object_id')},
            },
        ),
    ]
